name: tw_exp
channels:
  - conda-forge
  - defaults
dependencies:
- python==3.9.16
- plotly
- statsmodels
- seaborn
- matplotlib
- scipy
- numpy~=1.23.5
- pandas<=1.5.3
- ipywidgets
- numpyro
- pip
- streamlit
- pip:
  - causaltune
  - scikit-learn
  - pytest
  - pytest-cov
  - wise-pizza>=0.2.0
  - SQLAlchemy
  - snowflake_sqlalchemy
  - cloudpickle
  - jupyter
  - streamlit-extras
